# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('real_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=200)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
