# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0002_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='cpu_frequency',
            new_name='location_x',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='memory',
            new_name='location_y',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='cpu_number',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='node',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='node',
            name='memory_Speed',
        ),
        migrations.RemoveField(
            model_name='node',
            name='os',
        ),
        migrations.RemoveField(
            model_name='node',
            name='uri',
        ),
        migrations.AddField(
            model_name='node',
            name='node_file',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='node_ip',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
