# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_auto_20170306_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_active',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
