# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_node_node_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('node_id', models.IntegerField()),
                ('update_time', models.IntegerField()),
                ('evaluate_state', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=200)),
            ],
        ),
    ]
